version: 2

sources:
  - name: airbyte_amplitude
    description: raw data from Amplitude
    database: AIRBYTE_DB
    schema: AIRBYTE_SCHEMA
    tables:
      - name: _airbyte_raw_amplitude_events
        
        
models:
  - name: ampli_hubspot_dbt_model
    description: dbt model for Amplitude integration
    
    columns:
      - name: license_subscription_id
        description: License Subscription ID from Chargebee
      
      - name: start_version
        description: Version of Strapi at the start of the project

      - name: current_version
        description: Current version of Strapi

      - name: number_of_roles
        description: Number of roles that a project currently has

      - name: number_of_users
        description: Number of admin panel users that the project currently has
      
      - name: i_18_locales
        description: Number of I18 locales in the project

      - name: i_18_content_types
        description: Number of I18 content types in the project
      
      - name: plugins
        description: Plugins in use by the project

      - name: providers
        description: Project providers
      
      - name: license_type
        description: Type of license project is on

      - name: license_is_trial
        description: Indicates if license is trial

      - name: project_type
        description: Project type

      - name: event_time
        description: Time when the event occured
      

